### ISSUE TITLE
it stops working

### ISSUE THREAD

**Issue by mmiat** [jasonjoh/php-calendar#3]
I've used this library for more than 1 year, but monday it stops working
after I login, I return to my app and it gives me this error: "An error occurred: Error retrieving access token: Token request returned HTTP error 401"
[here](http://stackoverflow.com/questions/38648978/azure-ad-oauth2-access-token-request-error-400-bad-request) I found someone with similar problem, he says that in the url we need to add the Azure tenant id. Someone has the same problem? This trick works? Thanks

**Comment by mmiat** [comment]
thanks for reply
I think I've browsed ALL microsoft site, and I can't found where I've to create a new secret. unbelievable....
in my profile I view my apps, but I can't do nothing but revoke (why I can revoke but not create / manage? it's a mystery....)
I've tried to access azure portal, but there are no apps
thanks

**Comment by jasonjoh** [comment]
https://github.com/jasonjoh/office365-azure-guides/blob/master/RegisterAnAppInAzure.md should point you in the right direction.

**Comment by mmiat** [comment]
I've tried but I can't find it
but I'm not office 365 admin, maybe something is changed and I've no more access to my own apps?
thanks again
