### ISSUE TITLE
Error due to no consent

### ISSUE THREAD

**Issue by Danbardo** [jasonjoh/php-calendar#5]
Hey Jason,

I have uploaded everything to my web server and managed to get it working up until getTokenFromAuthCode.

I am receiving a 400 error with the below message:
"error":"invalid_grant","error_description":"AADSTS65001: The user or administrator has not consented to use the application with ID...."

I have granted permission through the Azure AD panel, and I also granted permission on first login. I am not sure why it's still asking for consent?

![image](https://user-images.githubusercontent.com/17368379/28564904-de20372a-716d-11e7-8dab-39e933c3df85.png)

I was also wondering, can I read a users calendar if their Office 365 is associated with another organisation? I am trying to make read staff calendars to use in an external website where people outside of the organisation can view calendars and request meetings. Whenever I try to login to the app I have created using a staff email, from another organisation, I get an error saying "The application could not be found under the organisation ...."
Edit; This works for apps made in Azure AD by switching Multi-Tenant on, but there is no option in Outlook Dev Portal.

Edit:
One other thing I noticed is that when I register an app using the Outlook Dev Portal and use the Password as the client secret, it returns and error stating the client secret is incorrect.

AADSTS70002: Error validating credentials. AADSTS50012: Invalid client secret is provided.

Is the password generated on the Outlook Dev Portal not the client secret?

Thanks in advance, sorry to bother you.

Closed:
Got the Javascript repo working

**Comment by jasonjoh** [comment]
From your screenshot you granted Application Permissions, but the sample needs Delegated Permissions. The difference here is that Delegated Permissions are the sort where a user can allow the app to act on their behalf (which is what this sample does), and Application Permissions are where an organization administrator can allow the app to access information without acting as a user.

For this sample, you should be registering the app in Azure AD portal.

Yes, you can access users in other organizations if you turn on the Multi-tenant option on your app. They will have to go and log in like anyone else.

**Comment by Danbardo** [comment]
Thanks so much Jason, it works now. The reason I started looking at the Outlook Dev Portal generated apps is because I've the current app on a trial business account. Is there anyway to set this up with my free Outlook account?

I just want to make sure I am understanding this correctly. I can use the request token at any time to generate another token and load the users calendar? For example, I could store the tokens, then every day, or week, I can use the refresh token to get another token?

**Comment by jasonjoh** [comment]
You can use the App Registration Portal generated apps here, but it would require some code changes. You can see a PHP sample that works with those kinds of registrations in my php-tutorial repo.

The refresh token can be used at any time with some limitations. They expire after 14 days from issuing, but each time you refresh, you get a new one, meaning the 14 day counter is reset. So you should only expire if you don't refresh for 14 days for some reason :).

**Comment by Danbardo** [comment]
Hey Jason,

Sorry I didn't respond any further,

Thanks for all your help!
