### ISSUE TITLE
App Only

### ISSUE THREAD

**Issue by knox2** [jasonjoh/php-calendar#6]
Hi Jason,

Can this be used for wep api apps for sending emails. I was using the ms graph api but it has limitations on attachments. can this be configured to authenticate without user interaction

**Comment by jasonjoh** [comment]
This is beyond the scope of this sample. If you want to authenticate without user interaction, you should be using the [client credential flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds) using a certificate.

**Comment by knox2** [comment]
Do you have an example of php using credential flow?

**Comment by jasonjoh** [comment]
No, sorry.

**Comment by knox2** [comment]
Its okay thanks. I've tried following other languages examples but I'm stuck at the following error:

```
{"error":"invalid_client","error_description":"AADSTS70002: Error validating credentials. AADSTS50012: Client assertion contains an invalid signature. [Reason - The key was not found., Thumbprint of key used by client: 'xxxxxx', Configured keys: [Key0:Start=01/08/2018, End=01/08/2019, Thumbprint=yyyyyy]]
Trace ID: $TID
Correlation ID: $ID
Timestamp: 2018-01-08 18:19:32Z","error_codes":[70002,50012],"timestamp":"2018-01-08 18:19:32Z","trace_id":"$TID","correlation_id":"$ID"} 
```

**Comment by knox2** [comment]
Solved it thanks.
