### ISSUE TITLE
futher tutorial (edit update delete an event in office 365 calendar )

### ISSUE THREAD

**Issue by rammohanreddy7** [jasonjoh/php-calendar#8]
hi jasonjoh, 

will you please give me some ideas or extended tutorial links for this ,  to edit update , delete an event .

present i was implemented  adding an event to calendar and reading the events ..

thanks,
rammohan.

**Comment by jasonjoh** [comment]
To update or delete, you need to get the `Id` of the item, then build your URL to the item like `/me/events/{id}`.

Delete is simply `DELETE /me/events/{id}`. Update is `PATCH /me/events/{id}`, with the body of the request being a JSON payload with the properties you want to update.
